import type { EnergyDrink } from "@/lib/types"

export const DEMO_DRINKS: EnergyDrink[] = [
  {
    id: "demo-monster-ultra-violet",
    brand: "Monster",
    flavor: "Ultra Violet",
    volumeMl: 500,
    rating: 9,
    comment: "Very nice flavor",
    shelf: 1,
    slot: 3,
    createdAt: "2026-01-04T12:00:00.000Z",
  },
  {
    id: "demo-red-bull-original",
    brand: "Red Bull",
    flavor: "Original",
    volumeMl: 250,
    rating: 8,
    comment: "Classic and sharp",
    shelf: 1,
    slot: 5,
    createdAt: "2026-01-08T12:00:00.000Z",
  },
  {
    id: "demo-monster-mango-loco",
    brand: "Monster",
    flavor: "Mango Loco",
    volumeMl: 500,
    rating: 10,
    comment: "Best mango so far",
    shelf: 1,
    slot: 2,
    createdAt: "2026-01-15T12:00:00.000Z",
  },
  {
    id: "demo-adrenaline-rush",
    brand: "Adrenaline Rush",
    flavor: "Original",
    volumeMl: 449,
    rating: 7,
    comment: "Sweet, a bit harsh",
    shelf: 1,
    slot: 1,
    createdAt: "2026-02-02T12:00:00.000Z",
  },
  {
    id: "demo-red-bull-tropical",
    brand: "Red Bull",
    flavor: "Tropical",
    volumeMl: 250,
    rating: 8,
    comment: "Light summer taste",
    shelf: 1,
    slot: 6,
    createdAt: "2026-02-18T12:00:00.000Z",
  },
  {
    id: "demo-monster-ultra-white",
    brand: "Monster",
    flavor: "Ultra White",
    volumeMl: 500,
    rating: 9,
    comment: "Clean citrus finish",
    shelf: 1,
    slot: 4,
    createdAt: "2026-03-01T12:00:00.000Z",
  },
]
